var translationEN = {
		CITYNAME:'City name : ',
		ZIPCODE:'ZIP code : ',
		COUNTRY:'Country : ',
		LATITUDE:'Latitude : ',
		LONGITUDE:'Longitude : ',
		SEARCHNAME:'Search by name',
		SEARCHZIP:'Search by ZIP code',
		SEARCHCOORD:'Search by coordinates',
		WEATHER:'Weather',
		TEMPERATURE:'Temperature',
		FORECAST:'-choose forecast-',
		DAY:' day',
		DAYS:'days',
		ERRCASE1:'Connection problem with database',
		ERRCASE2:'No city found',
		ERRCASE3:'ZIP codes not available in this country',
		BUTTON_LANG_EN:'English',
		BUTTON_LANG_FR:'French'
};

var translationFR = {
		CITYNAME:'Nom de la ville : ',
		ZIPCODE:'Code postal : ',
		COUNTRY:'Pays : ',
		LATITUDE:'Latitude : ',
		LONGITUDE:'Longitude : ',
		SEARCHNAME:'Recherche par nom',
		SEARCHZIP:'Recherche par code postal',
		SEARCHCOORD:'Recherche par coordonnées',
		WEATHER:'Météo',
		TEMPERATURE:'Température',
		FORECAST:'-choix prévisions-',
		DAY:' jour',
		DAYS:'jours',
		ERRCASE1:'Problème de connexion avec la base de données',
		ERRCASE2:'Aucune ville trouvée',
		ERRCASE3:'Ce pays n\'utilise pas les codes postaux',
		BUTTON_LANG_EN:'Anglais',
		BUTTON_LANG_FR:'Français'
};